# Generated by Django 2.0.5 on 2018-06-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSequenceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('voting_allowed', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynpoll.Question')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynpoll.QuestionSequence')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ip', models.GenericIPAddressField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynpoll.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynpoll.Question')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynpoll.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='questionsequenceitem',
            unique_together={('sequence', 'question')},
        ),
    ]
