# Generated by Django 2.0.5 on 2018-05-16 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynpoll', '0002_added_vote_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSequenceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynpoll.Question')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynpoll.QuestionSequence')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='questionsequenceitem',
            unique_together={('sequence', 'question')},
        ),
    ]
