# Generated by Django 2.0.5 on 2018-06-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynpoll', '0003_question_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsequenceitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionsequenceitem',
            name='polling_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionsequenceitem',
            name='showing_results',
            field=models.BooleanField(default=False),
        ),
    ]
