# Generated by Django 2.0.5 on 2018-06-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynpoll', '0004_auto_20180608_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsequenceitem',
            old_name='polling_allowed',
            new_name='voting_allowed',
        ),
        migrations.RemoveField(
            model_name='questionsequenceitem',
            name='showing_results',
        ),
    ]
