# Generated by Django 2.0.5 on 2018-06-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynpoll', '0005_auto_20180608_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dynpoll.Question'),
            preserve_default=False,
        ),
    ]
